image: Visual Studio 2017
install:
  - choco install gitversion.portable -pre -y
  - dotnet tool install coveralls.net --tool-path ./tools
test: off
assembly_info:
  patch: false
nuget:
  disable_publish_on_pr: true
environment:
  COVERALLS_REPO_TOKEN:
    secure: MrIsjBB5ll9iSPzArtLT7hIjzhERKvgOZVt9b6yaZnfsSx5m+L708JwFTAEJJllw
  NUGET_API_KEY:
    secure: lrwREUV4nO99AU0A6xVx/MNF0BaJc8A1B8dwEGMLqmYKGqD5E7PJ/IC9RHcle6pk
  NUGET_SOURCE: https://api.nuget.org/v3/index.json
before_build:
  - ps: gitversion /l console /output buildserver
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - tools -> appveyor.yml

build_script:
  - cmd: dotnet test /v:m
  - cmd: dotnet pack /v:m --configuration Release
  - cmd: tools\csmacnz.Coveralls.exe --opencover -i testresults\FluentAssertions.Autofac.Tests.Coverage.xml
  - cmd: if "%APPVEYOR_REPO_TAG%" == "true" dotnet nuget push *.nupkg -k %NUGET_API_KEY% -s %NUGET_SOURCE%
