image: Visual Studio 2017
install:
  - choco install gitversion.portable -pre -y
test: off
assembly_info:
  patch: false
nuget:
  disable_publish_on_pr: true
environment:
  apiKey:
    secure: lrwREUV4nO99AU0A6xVx/MNF0BaJc8A1B8dwEGMLqmYKGqD5E7PJ/IC9RHcle6pk
before_build:
  - ps: gitversion /l console /output buildserver
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

build_script:
  - cmd: 'dotnet test /v:m && dotnet pack /v:m'
  #- TODO: coveralls upload testresults\*.Coverage.xml
  #- TODO: cmd: if "%APPVEYOR_REPO_TAG%" == "true" dotnet nuget push -k %apiKey%
