image: Visual Studio 2019
test: off
assembly_info:
  patch: false
nuget:
  disable_publish_on_pr: true
cache:
  - tools -> tools\packages.config
environment: # https://ci.appveyor.com/tools/encrypt
  SONAR_LOGIN:
    secure: l2/mdQdg/lTP5RDqDK8CeiEqwD5OCb9xKuF6MEbZHWMost5D9CpGAeuIm303tgUk
  NUGET_API_KEY:
    secure: 1gZfYXDnZKFT1JddFudQ6YWtaY3b5dd9TRyGgMWAvDcaemYinhdGIzRa21VKSGx5

# Note that 'ps' will continue on non-terminating errors, cf.:
# - https://www.appveyor.com/docs/build-configuration/#interpreters-and-scripts
# - https://github.com/SharpeRAD/Cake.Powershell/blob/master/appveyor.yml#L5
build_script:
  - cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command .\build.ps1 -Target "CiBuild"
