image: Visual Studio 2017
install:
  - choco install gitversion.portable -pre -y
  - dotnet tool install coveralls.net --tool-path ./tools
test: off
assembly_info:
  patch: false
nuget:
  disable_publish_on_pr: true
environment:
  apiKey:
    secure: lrwREUV4nO99AU0A6xVx/MNF0BaJc8A1B8dwEGMLqmYKGqD5E7PJ/IC9RHcle6pk
  COVERALLS_REPO_TOKEN:
    secure: MrIsjBB5ll9iSPzArtLT7hIjzhERKvgOZVt9b6yaZnfsSx5m+L708JwFTAEJJllw
before_build:
  - ps: gitversion /l console /output buildserver
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - tools -> appveyor.yml
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'

build_script:
  - cmd: dotnet test /v:m
  - cmd: dotnet pack /v:m
  - cmd: tools\csmacnz.Coveralls.exe --opencover -i testresults\FluentAssertions.Autofac.Tests.Coverage.xml
  #-cmd: if "%APPVEYOR_REPO_TAG%" == "true" dotnet nuget push -k %apiKey%
